// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdvFveHqrQsslqGSHw0Jzkti-tzOlSKRA',
    appId: '1:379999015667:web:159ab8cbd9da6607261d86',
    messagingSenderId: '379999015667',
    projectId: 'event-app-e62e0',
    authDomain: 'event-app-e62e0.firebaseapp.com',
    storageBucket: 'event-app-e62e0.firebasestorage.app',
    measurementId: 'G-1XMKDXQ1RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-79--Y8P0Rzr4thlM1H-8dEM5zI_8mo',
    appId: '1:379999015667:android:59265689698756b3261d86',
    messagingSenderId: '379999015667',
    projectId: 'event-app-e62e0',
    storageBucket: 'event-app-e62e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5HOP63OAsRmXy3Fu5-h7JrE0FVz3UGww',
    appId: '1:379999015667:ios:c7af9cd485755dc1261d86',
    messagingSenderId: '379999015667',
    projectId: 'event-app-e62e0',
    storageBucket: 'event-app-e62e0.firebasestorage.app',
    androidClientId:
        '379999015667-cg3mau493evglap32pu7dpput7f12cvq.apps.googleusercontent.com',
    iosClientId:
        '379999015667-476uactqdsvni12eu2v0c8fb5qmfkmf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5HOP63OAsRmXy3Fu5-h7JrE0FVz3UGww',
    appId: '1:379999015667:ios:c7af9cd485755dc1261d86',
    messagingSenderId: '379999015667',
    projectId: 'event-app-e62e0',
    storageBucket: 'event-app-e62e0.firebasestorage.app',
    androidClientId:
        '379999015667-cg3mau493evglap32pu7dpput7f12cvq.apps.googleusercontent.com',
    iosClientId:
        '379999015667-476uactqdsvni12eu2v0c8fb5qmfkmf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdvFveHqrQsslqGSHw0Jzkti-tzOlSKRA',
    appId: '1:379999015667:web:bd2b49cf5d9ddc30261d86',
    messagingSenderId: '379999015667',
    projectId: 'event-app-e62e0',
    authDomain: 'event-app-e62e0.firebaseapp.com',
    storageBucket: 'event-app-e62e0.firebasestorage.app',
    measurementId: 'G-R3LWRKBYV5',
  );
}
